---
# handlers file for beats

- name: restart beat
  service:
    name: "{{ beat }}"
    state: restarted
    enabled: yes
  when:
    - start_service | bool
    - restart_on_change | bool
    - not beats_started.changed
    - beat_install.changed
